SELECT * FROM db.booktype;
use db;
select count(distinct title) from booktype;
alter table booktype change column percents gender varchar(20);
select  count( gender in ("m"))  from booktype;
alter table expenses add column total long ;
insert into expenses values(1,"jan",2000,2500,3000,4000,3000,4500,5000,450000);
insert into expenses (month,exp1,exp2,exp3,exp4) values("feb",6500,3000,5000,240);
update expenses set exp1=0 or exp7=0  where exp1 is null or exp7 is null;
insert into expenses values(1,"jan",1000,2000,3000,4000,10000);
insert into expenses values(2,"man",1000,2000,3000,6000,12000);
select* from booktype where  gender  in("f")and book_id<7;
select * from booktype where book_id<13 and(title like "f%" or title like "%a") and gender in ("m");
select * ,if(book_id>4 and  gender in("m"),"high value books only for male ","low value books only for female") from booktype;
insert into booktype (title,price) values("bootsrap",432);
select * from booktype where  gender  is not null;
update booktype set title = "" where book_id=2;
select count(title) as no_of_title,title from booktype where (title like "p%" or title like"A%") group by book_id having no_of_title limit 3;
