update   class set gender='M';
update   class set gender='F' where id=12;
update   class set gender='F' where id=13;
update   class set gender='F' where id=14;
update   class set gender='F' where id=15;
update   class set gender='F' where id=16;
update   class set gender='F' where id=17;
update   class set gender='F' where id=18;
update   class set gender='F' where id=19;
update   class set gender='F' where id=20;
update   class set gender='F' where id=21;
update   class set gender='F' where id=24;
update   class set gender='F' where id=25;
update   class set gender='F' where id=31;
update   class set gender='F' where id=34;
update   class set gender='F' where id=36;
update   class set gender='F' where id=35;
select * from class ;
delete from class where name="sowmiya" ;
delete from  class where id=35;
delete from class where id in (32,33,34);
select *from class where age>20 and finalgrade in("c") and gender in ("M") ;
select * from class where name like "a%";
select * from class where (name like "a%" or name like "b%") and (name like"%a");
select  * from class where name like "__m%a";
select * from class where gender in("m");
select * from class where gender not in("m");
select * from class where gender is null;
select * from class where gender is not null and id>13;
select * from class order by age;
select * from class order by finaLgrade desc;
select * from class order by name desc limit 10;
desc class;
select finalgrade,count(finalgrade) as total_person from class group by finalgrade;
select gender,count(gender) as total_members from class group by gender;
select gender,count(gender) as total_members from class group by gender having count(gender) limit 1;
